---
title: "  "
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<br>
<br>
<br>
<br>
<br>
<br>
<br>

## Título da Palestra

<!--
<span style=" font-size: 32px; font-weight:bold; color:darkblue;">
 -
</span>

-->
<br>
<br>
<br>

## Resumo

<br>
<br>

<!--
<span style=" font-size: 20px; font-weight:bold; color:darkblue;">
Os fenômenos sociais são complexos e as democracias precisam de cidadãos que possam explorar, entender e raciocinar sobre evidências e informações fundamentadas em dados e resultados estatísticos. <br> <br>
Nessa conversa serão apresentadas iniciativas metodológicas, ferramentas computacionais, portais e artigos que apoiam e incentivam o desenvolvimento de cidadãos ativos e capacitados a participar de decisões da sociedade.
</span>


A disseminação do COVID- 19 no Brasil e no mundo ainda está cercada de incertezas mas já indicam que deverão acontecer mudanças relevantes na nossa vida. Serão feitas reflexões a respeito das que poderão ser positivas e que medidas para diminuir os efeitos negativos.-->

<br>
<br>
<br>

## Palestrante

<span style=" font-size: 32px; font-weight:bold; color:darkblue;">
Profa. Luciane Velasque  </span>
<br>
<br>
<br>


## Mediador(a)/Debatedor(a)

<span style=" font-size: 32px; font-weight:bold; color:darkblue;">Prof. Davi Alves</span>
<br>
<br>
<br>

## Horário

<span style=" font-size: 32px; font-weight:bold; color:darkblue;">14:00 horas</span>

<br>
<br>

## Link para o evento

<span style=" font-size: 32px; font-weight:bold; color:darkblue;">
 <a href="https://meet.google.com/mrw-qgvc-svf">meet.google.com/mrw-qgvc-svf</a> 
</span>

<br>
<br>



## Programação: Próximas datas

```{r,echo=FALSE}
minhasdatas <- as.Date(c("2020-06-22","2020-06-29",
                         "2020-07-06","2020-06-13","2020-06-20",
                         "2020-06-27"))
minhahora<-rep("14 Horas",6)
#format(minhasdatas, format="%d%m%Y")
Palestrante<-c("Letícia Raposo","Bruno Simões","Felipe Ribeiro"
               ,"Davi Alves","Beatriz Cunha","Steven Ross")

Link<- c("meet.google.com/cfo-zhba-oyr",
"meet.google.com/xjh-fimh-zxd",
"meet.google.com/uns-ycoi-bzk",
"meet.google.com/adf-ftxf-idn",
"meet.google.com/phz-tmge-tqs",
"meet.google.com/aeu-aahe-kws")
prog<-data.frame(format(minhasdatas, format="%d %m %Y"),minhahora,Palestrante,Link)
colnames(prog)<-c("Datas","Hora","Palestrante","Link")

DT::datatable(prog, class = 'cell-border stripe',rownames=FALSE)
#DT::datatable(head(iris), editable = 'cell')

#estimativa_do_numero_de_pessoas<-c(23,60)
```

<br>
<br>


## Eventos anteriores

```{r,echo=FALSE}
minhasdatas <- as.Date(c("2020-05-25"
                         ,"2020-06-01","2020-06-08"))
#                         "2020-06-15","2020-06-22","2020-06-29",
#                         "2020-07-06","2020-06-13","2020-06-20",
#                         "2020-06-27"))
minhahora<-rep("14 Horas",3)
#format(minhasdatas, format="%d%m%Y")
Palestrante<-c("Tereza Barbosa","Pimentel/Vinicius","Alexandre Silva")
               #,"Luciane Velasque","Letícia Raposo",
#               "Bruno Simões","Felipe Ribeiro","Davi Alves",
#               "Beatriz Cunha","Steven Ross")

Titulo<- c("Perspectivas para nossa vida pessoal e acadêmica pós pandemia", "Práticas didático-pedagógicas e a formação de professores para o exercício responsável da docência online","Educação Estatística na promoção do engajamento cívico")

Link<- c("meet.google.com/wqk-fcod-eps","meet.google.com/bwt-pmee-acz","https://www.meet.google.com/axv-azca-rwq")

#"meet.google.com/mrw-qgvc-svf",
#"meet.google.com/cfo-zhba-oyr",
#"meet.google.com/xjh-fimh-zxd",
#"meet.google.com/uns-ycoi-bzk",
#"meet.google.com/adf-ftxf-idn",
#"meet.google.com/phz-tmge-tqs",
#"meet.google.com/aeu-aahe-kws")

youtube<-c(NA,"https://youtu.be/Ai6wcDdHhmc",NA)

prog<-data.frame(format(minhasdatas, format="%d %m %Y"),minhahora,Palestrante,Titulo, youtube)
colnames(prog)<-c("Datas","Hora","Palestrante","Título","Link")

DT::datatable(prog, class = 'cell-border stripe',rownames=FALSE)
#DT::datatable(head(iris), editable = 'cell')
```

