---
title: "  "
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r,echo=FALSE}
minhasdatas <- as.Date(c("2020-05-25","2020-06-01","2020-06-08","2020-06-15","2020-06-22","2020-06-29","2020-07-06","2020-07-13","2020-07-20","2020-07-27","2020-08-03","2020-08-31"))

Palestrante<-c("Tereza Barbosa","Pimentel","Alexandre Silva","Luciane Velasque","Letícia Raposo","Bruno Simões","Felipe Ribeiro","Davi Alves","Beatriz Cunha","Steven Ross","Vinícius Israel","Prof. Ponce de Leon")

Titulo<- c("Perspectivas para nossa vida pessoal e acadêmica pós pandemia", "Práticas didático-pedagógicas e a formação de professores para o exercício responsável da docência online","Educação Estatística na promoção do engajamento cívico","O Pandemônio da Pandemia","Atividades e Ferramentas para o Ensino Online","Projetos no ensino superior e pesquisas: ações e reflexões de um professor esperançoso","Google Meet, Probabilidade e R (não necessariamente nesta ordem): um pouco da minha quarentena","'Então você não está trabalhando?' – O que um professor universitário tem feito durante a quarentena?","Meu universo paralelo: Relatos de uma professora em isolamento social","Rython (R + Python): Tidy little things","O que fazer? Reflexões sobre o retorno remoto","Técnicas estatísticas clássicas aplicadas ao curso da pandemia")

youtube<-c("https://youtu.be/bZl3-HJdLlo","https://youtu.be/Ai6wcDdHhmc","https://youtu.be/A42EgBiG3Zs","https://youtu.be/2bTlNeYpW1E","https://youtu.be/x_nG91PiuKI","https://youtu.be/F3thfDwArZY","https://youtu.be/ohlzTdTZqFs","https://youtu.be/zP0a6f-7OnM","https://youtu.be/cpanmwkB0Pk","https://youtu.be/fAwsXfoYRWg","https://www.youtube.com/watch?v=4A5aqGnwHcc","https://www.youtube.com/watch?v=UuR79Zh6WCQ&feature=youtu.be")

estimativa_do_numero_de_pessoas<-c(23,59,20,26,50,26,21,19,15,NA,19,17)

estimativa_do_numero_de_pessoas_assicrona<-c(29,127,21,16,74,19,11,7,13,4,NA,NA)

total<-sum(estimativa_do_numero_de_pessoas,na.rm = TRUE) + sum(estimativa_do_numero_de_pessoas_assicrona,na.rm = TRUE)

prog<-data.frame(format(minhasdatas, format="%d %m %Y"),Palestrante,Titulo, youtube,estimativa_do_numero_de_pessoas,estimativa_do_numero_de_pessoas_assicrona)
colnames(prog)<-c("Datas","Palestrante","Título","Link","Quantidade de pessoas 1","Quantidade de pessoas 2")


```

<br>
<br>
<br>
<br>
<br>
<br>
<br>


## Alguns Resultados

#### Aqui você vai encontrar o link para o evento, a estimativa do número de pessoas síncronas e assíncronas (até 11/08).

<br>
<br>

#### Até o momento, o total de pessoas (síncronas e assíncronas) que participaram do DMQ Talks foi: `r total` pessoas
     
<br>
<br>

#### Distrubuição por evento

```{r,echo=FALSE}
DT::datatable(prog, class = 'cell-border stripe',rownames=FALSE,
        caption = htmltools::tags$caption(
        style = 'caption-side: bottom; text-align: center;',
    'Pessoas 1: Estimativa do numero de pessoas (síncrona) |            
     Pessoas 2: Estimativa do numero de pessoas  (assíncrona - até 11/08)'))

```

Para entrar em contato, por favor, acesse o site do [GAE](http://gae.uniriotec.br/)